apiVersion: v1
kind: Service
metadata:
    name: postgres
spec:
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
---
apiVersion: v1
kind: Endpoints
metadata:
    name: postgres
subsets:
    - addresses:
        - ip: 192.168.39.1
      ports:
        - port: 5432
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq-dashboard
spec:
  selector:
    app: rabbitmq
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 15672
    targetPort: 15672
---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
         app: rabbitmq
    spec:
      containers:
      - image: rabbitmq:3.7-management-alpine
        name: rabbit-mq
        ports:
        - containerPort: 15671
        - containerPort: 5671
