apiVersion: batch/v1
kind: Job
metadata:
  name: publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        image: media-analyzer
        args: ["publishers", "--postgres-ip", "192.168.39.1"]
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller
  labels:
    app: puller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puller
  template:
    metadata:
      labels:
        app: puller
    spec:
      containers:
      - name: puller
        image: media-analyzer
        args: ["pull", "--postgres-ip", "192.168.39.1"]
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: process
  labels:
    app: process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
    spec:
      containers:
      - name: process
        image: media-analyzer
        args: ["process", "--postgres-ip", "192.168.39.1"]
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: media-analyzer
        args: ["store", "--postgres-ip", "192.168.39.1"]
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload
  labels:
    app: upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload
  template:
    metadata:
      labels:
        app: upload
    spec:
      containers:
      - name: upload
        image: media-analyzer
        args: ["upload"]
        imagePullPolicy: Never
