apiVersion: batch/v1
kind: Job
metadata:
  name: publisher
spec:
  template:
    spec:
      containers:
      - name: publisher
        image: media-analyzer
        args: ["publishers", "--queue-ip", "10.100.148.223",
                             "--postgres-ip", "192.168.1.11"]
        imagePullPolicy: Never
      restartPolicy: Never
  backoffLimit: 4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: puller-deployment
  labels:
    app: puller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: puller
  template:
    metadata:
      labels:
        app: puller
    spec:
      containers:
      - name: puller
        image: media-analyzer
        args: ["pull", "--queue-ip", "10.100.148.223",
                       "--postgres-ip", "192.168.1.11"]
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: process-deployment
  labels:
    app: process
spec:
  replicas: 1
  selector:
    matchLabels:
      app: process
  template:
    metadata:
      labels:
        app: process
    spec:
      containers:
      - name: process
        image: media-analyzer
        args: ["process", "--queue-ip", "10.100.148.223",
                          "--postgres-ip", "192.168.1.11"]
        imagePullPolicy: Never
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-deployment
  labels:
    app: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
  template:
    metadata:
      labels:
        app: store
    spec:
      containers:
      - name: store
        image: media-analyzer
        args: ["store", "--queue-ip", "10.100.148.223",
                        "--postgres-ip", "192.168.1.11"]
        imagePullPolicy: Never
